name: speed test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: |
        sudo apt-get install wget

    - name: run test
      run: |
        wget https://www.seedr.cc/zip/71100910?st=0a330f5dd68e85da43b8d2cfa4183a09917b776677d714bc7b8223b48f185a64&e=1572588834

    - name: change directory
      run: |
        cd /home/runner/work/scripts/scripts/
        ls -lh

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: my-artifact
        path: /home/runner/work/scripts/scripts